{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kk.plugin",
    "module": "singleclick",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "ywyxk4itvjaxre55hknx5z3e5i"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "singleclick-1.0.0.jar",
          "url": "singleclick-1.0.0.jar",
          "size": 29666,
          "sha512": "eda64725573173883e8d072264fad572eddff1cfb6a66665c7a38886c883b09d2143b2f08f026f687983259b52a4495d8fac68856389ceecf33db2c7455d4917",
          "sha256": "b96385602fb1271606d8a344eaf70e9a7d89ddc9ec3d47f377ccaabb55f0dd99",
          "sha1": "4457c7b84a67a61cd55c1857c7032be9193860dd",
          "md5": "1fdfcd05d0a3195f57b0ab120580163e"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "3.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "singleclick-1.0.0.jar",
          "url": "singleclick-1.0.0.jar",
          "size": 29666,
          "sha512": "eda64725573173883e8d072264fad572eddff1cfb6a66665c7a38886c883b09d2143b2f08f026f687983259b52a4495d8fac68856389ceecf33db2c7455d4917",
          "sha256": "b96385602fb1271606d8a344eaf70e9a7d89ddc9ec3d47f377ccaabb55f0dd99",
          "sha1": "4457c7b84a67a61cd55c1857c7032be9193860dd",
          "md5": "1fdfcd05d0a3195f57b0ab120580163e"
        }
      ]
    }
  ]
}
