{
  "formatVersion": "1.1",
  "component": {
    "group": "com.kk.plugin",
    "module": "singleclick",
    "version": "1.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.7.1",
      "buildId": "fvsku2wwzrahlm5jutd7fijtzi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "singleclick-1.0.0.jar",
          "url": "singleclick-1.0.0.jar",
          "size": 29666,
          "sha512": "164b8f7cc8797d5bfa93caf0525847c2b7409c1877e8ff2987dcac4274cf3bd09f29e9c1954d5a3b8c4692ae65d486931dadbac5e5e479f80d7b1dc227e742e1",
          "sha256": "69d32f2666d48b04ab0138e2b7336bb10c8d4535838dade36b638b6d28a9992b",
          "sha1": "a211d4dfe974f8eca4c6d5f05688e901d88e2285",
          "md5": "f884777d2bdcd0e7570ca90054d3707a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "4.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "singleclick-1.0.0.jar",
          "url": "singleclick-1.0.0.jar",
          "size": 29666,
          "sha512": "164b8f7cc8797d5bfa93caf0525847c2b7409c1877e8ff2987dcac4274cf3bd09f29e9c1954d5a3b8c4692ae65d486931dadbac5e5e479f80d7b1dc227e742e1",
          "sha256": "69d32f2666d48b04ab0138e2b7336bb10c8d4535838dade36b638b6d28a9992b",
          "sha1": "a211d4dfe974f8eca4c6d5f05688e901d88e2285",
          "md5": "f884777d2bdcd0e7570ca90054d3707a"
        }
      ]
    }
  ]
}
